name: Build and Deploy to App Center

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Create local.properties with SDK location
      run: |
        echo "sdk.dir=$ANDROID_SDK_ROOT" > ./android/local.properties
        echo "BASE_URL=\"${{ secrets.BASE_URL }}\"" >> ./android/local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      working-directory: ./android
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      working-directory: ./android

    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        token: ${{ secrets.APP_CENTER_TOKEN }}
        appName: skeat/SMonkey
        file: android/app/build/outputs/apk/debug/app-debug.apk # 빌드된 APK 파일의 경로
        group: Collaborators # 배포할 그룹의 이름
